# Site
name: "Quest"
title: "Quest"
description: "The Occasional Insights from a Reflective Voyager."
logo: "assets/images/logo.svg"
favicon: "assets/images/logo.svg"
baseurl: "/personal-blog"
google_analytics: "UA-46278016-1"
disqus: "quest-5"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  certyfreak:
    name: Abdul Aziz Ali Alhassan
    display_name: certyfreak
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: azizalialhassan@gmail.com
    web: certyfreak.com
    twitter: https://twitter.com/certyfreak
    description: "An apprentice aiming to grok software craftsmanship."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    category: "/category/:name/"
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
